/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelImagenFondo.java
 *
 * Created on 10-ene-2012, 11:08:46
 */
package Vista;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Gonzalo
 */
public class JPanelImagenFondo extends javax.swing.JPanel {

    /** Creates new form JPanelImagenFondo */
    private ImageIcon imageIcon = new ImageIcon(getClass().getResource("/Imagenes/ruleta5.jpg"));
    public JPanelImagenFondo() {
        initComponents();
        Dimension d= new Dimension(imageIcon.getIconWidth(), imageIcon.getIconHeight());
        setSize(d);
        setOpaque(false); 
    }
     @Override  
    public void paint(Graphics g) {  
        g.drawImage(imageIcon.getImage(), 0, 0, getWidth(), getHeight(), null);  
        super.paint(g);  
    }  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
