/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgApuestas.java
 *
 * Created on 03-ene-2012, 18:17:47
 */
package Vista;

import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import juego.Dados.ModeloDados;

/**
 *
 * @author Antonio
 */
public class DlgApuestas extends javax.swing.JDialog {

    int apuesta;
    int tipoApuesta;
    int saldo;
    String apostado;
     ModeloDados modelo;

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }
     
    /** Creates new form DlgApuestas */
    public DlgApuestas(java.awt.Frame parent, boolean modal, ModeloDados modelo) {
        super(parent, modal);
        initComponents();
        this.modelo=modelo;
        jComboBox_TipoApuesta.addItem("Linea de Pase");//0
        jComboBox_TipoApuesta.addItem("Linea de No Pase");//1
        jComboBox_TipoApuesta.addItem("Zona");//2
        jComboBox_TipoApuesta.addItem("Gran 6 ");//3
        jComboBox_TipoApuesta.addItem("Gran 8 ");//4
        jComboBox_TipoApuesta.addItem("Craps ");//5
        jComboBox_TipoApuesta.addItem("Siete ");//6
        jComboBox_TipoApuesta.addItem("Dos ");//7
        jComboBox_TipoApuesta.addItem("Tres ");//8
        jComboBox_TipoApuesta.addItem("Doce ");//9
        jComboBox_TipoApuesta.addItem("Once ");//10
        apostado="";
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_Apuesta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_TipoApuesta = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jLabel1.setText("Introduzca la cantidad que apuesta");

        jTextField_Apuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_Apuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ApuestaActionPerformed(evt);
            }
        });
        jTextField_Apuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ApuestaKeyTyped(evt);
            }
        });

        jLabel2.setText("Elija el tipo de apuesta que desea realizar");

        jComboBox_TipoApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TipoApuestaActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Apuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jComboBox_TipoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Apuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_TipoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextField_ApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ApuestaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField_ApuestaActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    String aux = jTextField_Apuesta.getText();

    apuesta = Integer.parseInt(aux);

    tipoApuesta = jComboBox_TipoApuesta.getSelectedIndex();
    apostado="";
    dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void jComboBox_TipoApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TipoApuestaActionPerformed
}//GEN-LAST:event_jComboBox_TipoApuestaActionPerformed

private void jTextField_ApuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ApuestaKeyTyped
    
        char type =  evt.getKeyChar();
        int k = (int) type;
               apostado= apostado + type;
        
    
    if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {
        evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        apostado="";
        JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
    }
    if (k == 241 || k == 209) {
        evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        apostado="";
        JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
    }
    //saldo=modelo.getSaldo
   
//   System.out.println(modelo.getSaldo());
   System.out.println(Integer.parseInt(apostado));
     int as= Integer.parseInt(apostado);
     
   if(modelo.getSaldo() < as){
       evt.setKeyChar((char) KeyEvent.VK_CLEAR);
       JOptionPane.showMessageDialog(null, "No tienes dineroo suficiente!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
   }

    if (k == 10) {
        jTextField_Apuesta.transferFocus();
       
    }

}//GEN-LAST:event_jTextField_ApuestaKeyTyped
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox_TipoApuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField_Apuesta;
    // End of variables declaration//GEN-END:variables

    void setSaldo(int saldo) {
        this.saldo = saldo;
    }
    
    void setValorMaximo(){
       
       
    }
}
