/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IdiomaView.java
 *
 * Created on 29-dic-2011, 16:17:37
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;
import javax.imageio.ImageIO;

/**
 *
 * @author Miguel Angel Fuentes Cardenas
 */
public class IdiomaView extends javax.swing.JDialog {

    //IMAGEN DE FONDO
    Image imagen;
    private Properties defProps;

    public Properties getDefProps() {
        return defProps;
    }

    /** Creates new form IdiomaView */
    public IdiomaView(java.awt.Frame parent, boolean modal, int idioma) {
        super(parent, modal);
        initComponents();
        CasinoView a = (CasinoView) parent;
        a.setIdiomaVista(this);
        //LEO LA IMAGEN DE FONDO
        try {
            switch (idioma) {
                case 0://ESPANOL
                    imagen = ImageIO.read(new File("Recursos/espana.jpg"));
                    break;

                case 1://INGLES
                    imagen = ImageIO.read(new File("Recursos/inglaterra.jpeg"));
                    break;
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        //CENTRO EN LA PANTALLA DE APLICACION
        this.setLocationRelativeTo(parent);

        //CARGO EL IDIOMA
        CargarIdioma(idioma);
    }

    /**
     * Sobre escribo el metodo pintar para que dibuje el panel con
     * una imagen de fondo.
     * 
     * @param g 
     */
    @Override
    public void paint(Graphics g) {
        if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

        }

        super.paint(g);

    }

    private void CargarIdioma(int idioma) {
        String fichero = "";
        InputStream f;
        defProps = new Properties();

        switch (idioma) {
            case 0: //ESPANOL
                fichero = "Recursos/lenguajes_es_ES.properties";
                break;

            case 1: //INGLES
                fichero = "Recursos/lenguajes_en_GB.properties";
                break;
        }


        //CONFIGURO LA INTERFAZ EN FUNCION DEL IDIOMA
        try {
            f = new FileInputStream(fichero);
            defProps.load(f);

            this.BotonEstablecer.setText(defProps.getProperty("set"));
            this.LabelSelectLanguaje.setText(defProps.getProperty("select_languaje"));
            ListIdiomas.setModel(new javax.swing.DefaultComboBoxModel(new String[]{defProps.getProperty("spanish"), defProps.getProperty("english")}));
            ListIdiomas.setSelectedIndex(idioma);
            this.setTitle(defProps.getProperty("languaje"));

            f.close();
        } catch (IOException e) {
            System.err.println("Error al cargar idioma por defecto");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSelectLanguaje = new javax.swing.JLabel();
        ListIdiomas = new javax.swing.JComboBox();
        BotonEstablecer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LabelSelectLanguaje.setText("Seleccione Idioma:");

        BotonEstablecer.setText("jButton1");
        BotonEstablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstablecerActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(LabelSelectLanguaje)
                .add(18, 18, 18)
                .add(ListIdiomas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .add(BotonEstablecer)
                .add(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(LabelSelectLanguaje)
                    .add(ListIdiomas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(BotonEstablecer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BotonEstablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstablecerActionPerformed
    Properties defProps = new Properties();
    Integer idioma = this.ListIdiomas.getSelectedIndex();

    //ALAMACENO EL IDIOMA SELECCIONADO PARA QUE LA PROXIMA VEZ QUE SE ABRA
    //LA APLICACION SE ENCUENTRE EN EL IDIOMA SELECCIONADO
    try {
        //Obtengo las propiedades actuales
        InputStream fi = new FileInputStream("Recursos/config.properties");
        defProps.load(fi);
        fi.close();

        //modifico las 
        defProps.setProperty("default_languaje", idioma.toString());

        //almaceno propiedades
        OutputStream fo = new FileOutputStream("Recursos/config.properties");
        defProps.store(fo, null);
        fo.close();
    } catch (IOException e) {
        e.printStackTrace();
    }

    //ESTABLEZCO EL IDIOMA EN EL JFRAME CasionView
    ((CasinoView) this.getParent()).setIdioma(idioma);

    //CIERRO EL DIALOGO
    this.dispose();
}//GEN-LAST:event_BotonEstablecerActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEstablecer;
    private javax.swing.JLabel LabelSelectLanguaje;
    private javax.swing.JComboBox ListIdiomas;
    // End of variables declaration//GEN-END:variables
}
