/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelBackground.java
 *
 * Created on 03-ene-2012, 0:33:57
 */
package Vista;
import java.awt.Dimension;  
import java.awt.Graphics;  
import javax.swing.ImageIcon;  
  
/**
 *
 * @author Antonio
 */
public class JPanelBackground extends javax.swing.JPanel {

    /** Creates new form JPanelBackground */
    private ImageIcon imageIcon = new ImageIcon("imagenes/craps-table.gif");
    
    public JPanelBackground() {  
        initComponents();
        //esta linea hace que el JPanel tenga el mismo tamaño que la imagen  
        Dimension d= new Dimension(imageIcon.getIconWidth(), imageIcon.getIconHeight());
        //es necesarion setear el JPanel a Opaque false, de lo contrario la imagen no sera visible  
        setSize(d);
        setOpaque(false);  
    }  
    
     @Override  
    public void paint(Graphics g) {  
        g.drawImage(imageIcon.getImage(), 0, 0, getWidth(), getHeight(), null);  
        super.paint(g);  
    }  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
