/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelLogin.java
 *
 * Created on 30-dic-2011, 11:23:18
 */
package Vista;

import controlador.Controlador;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import javax.imageio.ImageIO;

/**
 *
 * @author Miguel Angel Fuentes Cardenas
 */
public class PanelLogin extends javax.swing.JPanel {

    //IMAGEN DE FONDO
    Image imagen;
    Controlador controller;
    CasinoView cv;
    
    /** Creates new form PanelLogin */
    public PanelLogin(int idioma, Controlador controller, CasinoView cv) {
        this.cv = cv;
        initComponents();
        this.controller=controller;
        
        //LEO LA IMAGEN DE FONDO
        try{
        imagen = ImageIO.read(new File("Recursos/login.jpg"));
        }catch(IOException e){
            e.printStackTrace();
        }
        
        //CARGO EL IDIOMA
        CargarIdioma(idioma);
    }
    
    
    private void CargarIdioma(int idioma){
        String fichero="";
        InputStream f;
        Properties defProps = new Properties();
        
        switch(idioma){            
            case 0: //ESPANOL
                fichero = "Recursos/lenguajes_es_ES.properties";
                break;
                
            case 1: //INGLES
                fichero = "Recursos/lenguajes_en_GB.properties";
                break;
        }
        
        
        //CONFIGURO LA INTERFAZ EN FUNCION DEL IDIOMA
        try{            
            f = new FileInputStream(fichero);
            defProps.load(f);
            
            this.LabelUser.setText(defProps.getProperty("user"));
            this.LabelCalve.setText(defProps.getProperty("password"));
            
            f.close();
        }catch(IOException e){
            System.err.println("Error al cargar idioma por defecto");
        }
    }
    
    
    /**
     * Sobre escribo el metodo pintar para que dibuje el panel con
     * una imagen de fondo.
     * 
     * @param g 
     */
    @Override
    public void paint(Graphics g) 
    {
        if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
        } else {
            setOpaque(true);
        }

        super.paint(g);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        LabelUser = new javax.swing.JLabel();
        LabelCalve = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        BotonRegistrar = new javax.swing.JButton();
        BotonEntrar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(756, 600));

        LabelUser.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        LabelUser.setText("Passwrod:");
        LabelUser.setBounds(10, 50, 67, 16);
        jLayeredPane1.add(LabelUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LabelCalve.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        LabelCalve.setText("User:");
        LabelCalve.setBounds(20, 20, 50, 16);
        jLayeredPane1.add(LabelCalve, javax.swing.JLayeredPane.DEFAULT_LAYER);
        usuario.setBounds(90, 10, 147, 28);
        jLayeredPane1.add(usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.setBounds(90, 40, 147, 28);
        jLayeredPane1.add(password, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });
        BotonRegistrar.setBounds(140, 90, 100, 29);
        jLayeredPane1.add(BotonRegistrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BotonEntrar.setText("Entrar");
        BotonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntrarActionPerformed(evt);
            }
        });
        BotonEntrar.setBounds(10, 90, 81, 29);
        jLayeredPane1.add(BotonEntrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(175, 175, 175)
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
   
}//GEN-LAST:event_passwordActionPerformed

private void BotonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntrarActionPerformed
    int puntos = this.controller.entrar(this.usuario.getText(), new String(this.password.getPassword()),cv);
    this.controller.ShowMensaje("Puntos: "+puntos);
}//GEN-LAST:event_BotonEntrarActionPerformed

private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
    int puntos = this.controller.registrarse(this.usuario.getText(), new String(this.password.getPassword()),cv);
    this.controller.ShowMensaje("Puntos: "+puntos);
}//GEN-LAST:event_BotonRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrar;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JLabel LabelCalve;
    private javax.swing.JLabel LabelUser;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
