/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelCartaAlta.java
 *
 * Created on 03-ene-2012, 15:59:48
 */
package Vista;

import controlador.ControladorCartaAlta;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SpinnerNumberModel;
import general.Casino;
import general.Jugador;

/**
 *
 * @author Miguel Angel Fuentes Cardenas
 */
public class PanelCartaAlta extends javax.swing.JPanel implements Observer {

    //IMAGEN DE FONDO
    Image imagen;
    Casino casino;
    Jugador jugador;
    ControladorCartaAlta controller;

    public JButton getBotonJugar() {
        return BotonJugar;
    }

    public void setBotonJugar(JButton BotonJugar) {
        this.BotonJugar = BotonJugar;
    }

    public JButton getBotonOtra() {
        return BotonOtra;
    }

    public void setBotonOtra(JButton BotonOtra) {
        this.BotonOtra = BotonOtra;
    }

    public JLabel getLabelApuesta() {
        return LabelApuesta;
    }

    public void setLabelApuesta(JLabel LabelApuesta) {
        this.LabelApuesta = LabelApuesta;
    }

    public JLabel getLabelJugador() {
        return LabelJugador;
    }

    public void setLabelJugador(JLabel LabelJugador) {
        this.LabelJugador = LabelJugador;
    }

    public JLabel getLabelPuntos() {
        return LabelPuntos;
    }

    public void setLabelPuntos(JLabel LabelPuntos) {
        this.LabelPuntos = LabelPuntos;
    }
    
    /** Creates new form PanelCartaAlta */
    public PanelCartaAlta(Casino casino, ControladorCartaAlta controller) {
        this.controller = controller;
        this.casino = casino;
        this.jugador = casino.getJugador();
        
        initComponents();
        
        //LEO LA IMAGEN DE FONDO
        try{
        imagen = ImageIO.read(new File("Recursos/carta_alta.jpg"));
        }catch(IOException e){
            e.printStackTrace();
        }
        
        //AGREGO A ESTA CLASE COMO OBSERVADORA DE JUGADOR
        this.jugador.addObserver(this);
        
        //Oculto el boton para jugar de nuevo
        this.BotonOtra.setVisible(false);
    }
    
    
    /**
     * Sobre escribo el metodo pintar para que dibuje el panel con
     * una imagen de fondo.
     * 
     * @param g 
     */
    @Override
    public void paint(Graphics g) 
    {
        if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
        } else {
            setOpaque(true);
        }

        super.paint(g);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelJugador = new javax.swing.JLabel();
        nombreJugador = new javax.swing.JTextField();
        LabelPuntos = new javax.swing.JLabel();
        puntuacion = new javax.swing.JTextField();
        LabelApuesta = new javax.swing.JLabel();
        apuesta = new javax.swing.JSpinner();
        BotonJugar = new javax.swing.JButton();
        BotonOtra = new javax.swing.JButton();
        LabelCartaJugador = new javax.swing.JLabel();
        LabelCartaCrupier = new javax.swing.JLabel();

        LabelJugador.setText("Jugador:");

        nombreJugador.setEditable(false);
        nombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJugadorActionPerformed(evt);
            }
        });

        LabelPuntos.setText("Puntos:");

        puntuacion.setEditable(false);
        puntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntuacionActionPerformed(evt);
            }
        });

        LabelApuesta.setText("Apuesta:");

        apuesta.setModel(new javax.swing.SpinnerNumberModel(10, 10, 100, 1));

        BotonJugar.setText("Jugar");
        BotonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugarActionPerformed(evt);
            }
        });

        BotonOtra.setText("otra vez");
        BotonOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOtraActionPerformed(evt);
            }
        });

        LabelCartaJugador.setIcon(new ImageIcon("Recursos/trasera.jpg"));

        LabelCartaCrupier.setIcon(new ImageIcon("Recursos/trasera.jpg"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(90, 90, 90)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(LabelApuesta)
                            .add(LabelJugador)
                            .add(LabelPuntos))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                            .add(apuesta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(puntuacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nombreJugador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(LabelCartaCrupier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(BotonJugar)
                    .add(layout.createSequentialGroup()
                        .add(BotonOtra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(305, 305, 305)
                        .add(LabelCartaJugador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(LabelJugador)
                            .add(nombreJugador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(puntuacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(LabelPuntos)
                            .add(BotonJugar))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(LabelApuesta)
                            .add(layout.createSequentialGroup()
                                .add(1, 1, 1)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BotonOtra)
                                    .add(apuesta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(38, 38, 38)
                        .add(LabelCartaCrupier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(107, 107, 107)
                        .add(LabelCartaJugador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void nombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJugadorActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nombreJugadorActionPerformed

private void puntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntuacionActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_puntuacionActionPerformed

private void BotonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugarActionPerformed
    int a = (Integer) this.apuesta.getValue();
    controller.CartaAlta(a,this.LabelCartaJugador, this.LabelCartaCrupier);
    this.BotonOtra.setVisible(true);
    this.BotonJugar.setVisible(false);//oculto el boton
    
}//GEN-LAST:event_BotonJugarActionPerformed

private void BotonOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOtraActionPerformed
    this.BotonJugar.setVisible(true);
    this.BotonOtra.setVisible(false);
    casino.jugarDeNuevo();
    this.LabelCartaCrupier.setIcon(new ImageIcon("Recursos/trasera.jpg") );
    this.LabelCartaJugador.setIcon(new ImageIcon("Recursos/trasera.jpg") );
}//GEN-LAST:event_BotonOtraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonJugar;
    private javax.swing.JButton BotonOtra;
    private javax.swing.JLabel LabelApuesta;
    private javax.swing.JLabel LabelCartaCrupier;
    private javax.swing.JLabel LabelCartaJugador;
    private javax.swing.JLabel LabelJugador;
    private javax.swing.JLabel LabelPuntos;
    private javax.swing.JSpinner apuesta;
    private javax.swing.JTextField nombreJugador;
    private javax.swing.JTextField puntuacion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        if(o == this.jugador){
            this.nombreJugador.setText(jugador.getNombre());
            this.puntuacion.setText(""+jugador.getPuntos());
            int actual =(Integer) apuesta.getValue();
//            System.out.println("Apuesta: "+actual);
            SpinnerNumberModel model = (SpinnerNumberModel)apuesta.getModel();
            model.setMaximum(jugador.getPuntos());
            model.setValue(actual);
//            apuesta.setModel(new javax.swing.SpinnerNumberModel(actual, 10, jugador.getPuntos(), 1));
            
        }
    }
}
